volumes:
  db_prod:

networks:
  mediastack:
    external: true

services:
  security-guru:
    image: security-guru:stable
    container_name: security-guru
    restart: unless-stopped
    env_file: .env
    networks:
      - mediastack
    ports:
      - ${WEB_PORT:?err}:3333
    labels:
      - traefik.enable=true
      - traefik.http.routers.security-guru.rule=Host(`${CLOUDFLARE_DNS_ZONE_PROD:?err}`)
      - traefik.http.routers.security-guru.entrypoints=web
      - traefik.http.services.security-guru.loadbalancer.server.scheme=http
