volumes:
  db_local:

services:
  mongo-local:
    image: mongo:latest
    container_name: mongo-local
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: securityguru
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?err}
    volumes:
      - db_local:/data/db
