name: isBuilding

on:
  pull_request:
    types:
      - opened
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set up yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      #      - name: Test
      #        uses: borales/actions-yarn@v4
      #        with:
      #          cmd: test

      #      - name: Merge develop -> main
      #        uses: devmasx/merge-branch@master
      #        with:
      #        type: now
      #        message: "Merge develop -> main"
      #        from_branch: develop
      #        target_branch: main
      #        github_token: ${{ secrets.CI_TOKEN }}
